apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ivolve-webapp-pvc
  namespace: ivolve-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi